-- ----------------------------------------------
-- Treesitter: Syntax and code navigation (https://github.com/nvim-treesitter/nvim-treesitter)
-- :help treesitter.txtt i
-- ----------------------------------------------
local keymap = require("user-keymap")

return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    config = require("nvim-treesitter.configs").setup({
        sync_install = false,
        ignore_install = { "cpp" },
        modules = {},
        auto_install = true,
        ensure_installed = {
            "bash",
            "comment",
            "dockerfile",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "gpg",
            "html",
            "ini",
            "javascript",
            "jq",
            "json",
            "lua",
            "luadoc",
            "luap",
            "markdown",
            "markdown_inline",
            "passwd",
            "python",
            "regex",
            "requirements",
            "ruby",
            "sql",
            "terraform",
            "toml",
            "tsv",
            "typescript",
            "vim",
            "vimdoc",
            "xml",
            "yaml",

            -- "astro",
            -- "awk",
            -- "bash",
            -- "c",
            -- "cmake",
            -- "comment",
            -- "css",
            -- "csv",
            -- "dockerfile",
            -- "git_config",
            -- "git_rebase",
            -- "gitattributes",
            -- "gitcommit",
            -- "gitignore",
            -- "go",
            -- "gomod",
            -- "gosum",
            -- "gowork",
            -- "gpg",
            -- "groovy",
            -- "html",
            -- "ini",
            -- "javascript",
            -- "jq",
            -- "json",
            -- "llvm",
            -- "lua",
            -- "luadoc",
            -- "luap",
            -- "make",
            -- "markdown",
            -- "markdown_inline",
            -- "ninja",
            -- "ocaml",
            -- "ocaml_interface",
            -- "ocamllex",
            -- "passwd",
            -- "python",
            -- "query",
            -- "regex",
            -- "requirements",
            -- "ruby",
            -- "rust",
            -- "scss",
            -- "sql",
            -- "terraform",
            -- "toml",
            -- "tsv",
            -- "typescript",
            -- "vim",
            -- "vimdoc",
            -- "xml",
            -- "yaml",
            -- "zig",
        },
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },
        indent = { enable = true },
        incremental_selection = {
            enable = true,
            disable = { "c" },
            keymaps = keymap.treesitter_maps.incremental_selection
        },
        textobjects = {
            select = {
                keymaps = keymap.treesitter_maps.textobjects
            },
            move = {
                enable = true,
                set_jumps = true, -- whether to set jumps in the jumplist
                goto_next_start = keymap.treesitter_maps.move.goto_next_start,
                goto_next_end = keymap.treesitter_maps.move.goto_next_end,
                goto_previous_start = keymap.treesitter_maps.move.goto_previous_start,
                goto_previous_end = keymap.treesitter_maps.move.goto_previous_end,
            },
            swap = {
                enable = true,
                swap_next = keymap.swap_next,
                swap_previous = keymap.swap_previous,
            },
        },
        dependencies = {
            "nvim-treesitter/nvim-treesitter-textobjects", -- https://github.com/nvim-treesitter/nvim-treesitter-textobjects
        },
        build = ":TSUpdate",
    }),
}
