# pre-commit configuration (https://pre-commit.com)
#
# To install pre-commit using:
#   * pip: `pip install pre-commit`
#   * pipx: `pipx install pre-commit`
#   * homebrew: `brew install pre-commit`
#
# Add pre-commit hook scripts to git
#   `pre-commit install`
---
repos:
  # Global
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Fixes
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

      # Checks
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch # main/master by default

#   - repo: https://github.com/oxsecurity/megalinter
#     rev: v7.2.1
#     hooks:
#       - id: megalinter-incremental # Faster, less thorough
#         stages:
#           - commit
#       - id: megalinter-full # Slower, more thorough
#         stages:
#           - push
