-- ----------------------------------------------
-- Indentation guides (https://github.com/lukas-reineke/indent-blankline.nvim)
-- :help indent_blankline.txt
-- ----------------------------------------------
return {
    "lukas-reineke/indent-blankline.nvim",
    name = "indent-blankline",
    lazy = false,
    opts = {
        char = "┊",
        context_char = "┊",
        context_char_blankline = "┊",
        show_current_context = true,
        show_current_context_start = false,
        show_current_context_start_on_current_line = false,
        show_end_of_line = false,
        show_first_indent_level = true,
        show_trailing_blankline_indent = true,
        disable_with_nolist = true,
        space_char = " ",
        strict_tabs = true,
        space_char_blankline = " ",
        use_treesitter = true,
        use_treesitter_scope = true,
        viewport_buffer = 50,
        buftype_exclude = {
            "terminal",
            "nofile",
            "quickfix",
            "prompt",
        },
        filetype_exclude = {
            "",
            "checkhealth",
            "help",
            "lspinfo",
            "man",
            "neo-tree",
            "packer",
            "qf",
        },
        context_patterns = {
            "class",
            "^func",
            "method",
            "^if",
            "while",
            "for",
            "with",
            "try",
            "except",
            "match",
            "arguments",
            "argument_list",
            "object",
            "dictionary",
            "element",
            "table",
            "tuple",
            "do_block",
            "Block",
            "InitList",
            "FnCallArguments",
            "IfStatement",
            "ContainerDecl",
            "SwitchExpr",
            "IfExpr",
            "ParamDeclList",
            "unless",
        }
    },
}
