[tool.yamlfix]
# Force double quotes for all strings
quote_type = "double"

# Maintain the same indentation as in the source file
indent_mapping = 2
indent_sequence = 2
indent_offset = 0

# Maintain same line width as the source (don't wrap)
line_length = 999

# Rules for line breaks
whitelines = 1
start_whitelines = 0
end_whitelines = 0
section_whitelines = 1

# Always include document start marker
explicit_start = true

# Don't include document end marker
explicit_end = false

# Enforce Unix line endings
line_ending = "\n"

# Disable flow style for mappings and sequences
sequence_style = false

# Disallow duplicate keys
allow_duplicate_keys = false

# Enforce comment style
comments_require_starting_space = true
comments_min_spaces_from_content = 2
comments_whitelines = 1

# Enable preserving key ordering to match yamllint
preserve_key_ordering = true
