---

name: devbox
root: ~/dev/${ORG_ROOT}/
pre:
  - umount -f ~/dev/${ORG_ROOT}/${ORG_NAME}/ 2>/dev/null
  - devbox up
  - devbox mount --to ~/dev/${ORG_ROOT}/${ORG_NAME}

  windows:
    - terminal:
      root: ~/dev/${ORG_ROOT}/${ORG_NAME}/src
      layout: main-horizontal
      panes:
        - vim
        - vim
        - bash
    - devbox:
      - ssh devbox
      - m-serve
