name: dev
root: ~/dev/measurabl
pre:
  - umount -f ~/dev/measurabl/msr/ 2>/dev/null
  - devbox up
  - devbox mount --to ~/dev/measurabl/msr
windows:
    - terminal:
        root: ~/dev/measurabl/msr
        layout: main-vertical
        panes:
          - bash
          - bash
    - devbox:
      - ssh devbox
      - m-serve
